/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"

#include "lora-layer-2.h"


flag PollFinal_IsConstraintValid(const PollFinal* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void PollFinal_Initialize(PollFinal* pVal)
{
	(void)pVal;


	(*(pVal)) = FALSE;
}

flag PollFinal_Encode(const PollFinal* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? PollFinal_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PollFinal_Decode(PollFinal* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_POLLFINAL;

	return ret  && PollFinal_IsConstraintValid(pVal, pErrCode);
}


flag SM_IsConstraintValid(const SM* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PollFinal_IsConstraintValid((&(pVal->p)), pErrCode);

	return ret;
}

void SM_Initialize(SM* pVal)
{
	(void)pVal;


	/*set p */
	PollFinal_Initialize((&(pVal->p)));
}

flag SM_Encode(const SM* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? SM_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode p */
	    ret = PollFinal_Encode((&(pVal->p)), pBitStrm, pErrCode, FALSE);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag SM_Decode(SM* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode p */
	ret = PollFinal_Decode((&(pVal->p)), pBitStrm, pErrCode);

	return ret  && SM_IsConstraintValid(pVal, pErrCode);
}


flag UA_IsConstraintValid(const UA* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PollFinal_IsConstraintValid((&(pVal->f)), pErrCode);

	return ret;
}

void UA_Initialize(UA* pVal)
{
	(void)pVal;


	/*set f */
	PollFinal_Initialize((&(pVal->f)));
}

flag UA_Encode(const UA* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? UA_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode f */
	    ret = PollFinal_Encode((&(pVal->f)), pBitStrm, pErrCode, FALSE);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag UA_Decode(UA* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode f */
	ret = PollFinal_Decode((&(pVal->f)), pBitStrm, pErrCode);

	return ret  && UA_IsConstraintValid(pVal, pErrCode);
}


flag SequenceNumber_IsConstraintValid(const SequenceNumber* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 127UL);
    *pErrCode = ret ? 0 :  ERR_SEQUENCENUMBER;

	return ret;
}

void SequenceNumber_Initialize(SequenceNumber* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}

flag SequenceNumber_Encode(const SequenceNumber* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? SequenceNumber_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 127);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag SequenceNumber_Decode(SequenceNumber* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 127);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_SEQUENCENUMBER;

	return ret  && SequenceNumber_IsConstraintValid(pVal, pErrCode);
}


flag SequenceNumberSpan_IsConstraintValid(const SequenceNumberSpan* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = SequenceNumber_IsConstraintValid((&(pVal->first)), pErrCode);
    if (ret) {
        ret = SequenceNumber_IsConstraintValid((&(pVal->last)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void SequenceNumberSpan_Initialize(SequenceNumberSpan* pVal)
{
	(void)pVal;


	/*set first */
	SequenceNumber_Initialize((&(pVal->first)));
	/*set last */
	SequenceNumber_Initialize((&(pVal->last)));
}

flag SequenceNumberSpan_Encode(const SequenceNumberSpan* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? SequenceNumberSpan_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode first */
	    ret = SequenceNumber_Encode((&(pVal->first)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode last */
	        ret = SequenceNumber_Encode((&(pVal->last)), pBitStrm, pErrCode, FALSE);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag SequenceNumberSpan_Decode(SequenceNumberSpan* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode first */
	ret = SequenceNumber_Decode((&(pVal->first)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode last */
	    ret = SequenceNumber_Decode((&(pVal->last)), pBitStrm, pErrCode);
	}   /*COVERAGE_IGNORE*/

	return ret  && SequenceNumberSpan_IsConstraintValid(pVal, pErrCode);
}


flag MissingFrames_IsConstraintValid(const MissingFrames* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case nr_PRESENT : 
            ret = SequenceNumber_IsConstraintValid((&(pVal->u.nr)), pErrCode);
            break;          
        case span_PRESENT : 
            ret = SequenceNumberSpan_IsConstraintValid((&(pVal->u.span)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_MISSINGFRAMES;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

void MissingFrames_Initialize(MissingFrames* pVal)
{
	(void)pVal;


	pVal->kind = nr_PRESENT;
	pVal->u.nr = 0UL;
}

flag MissingFrames_Encode(const MissingFrames* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? MissingFrames_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch(pVal->kind)
	    {
	    case nr_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 1);
	    	ret = SequenceNumber_Encode((&(pVal->u.nr)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case span_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 1);
	    	ret = SequenceNumberSpan_Encode((&(pVal->u.span)), pBitStrm, pErrCode, FALSE);
	    	break;
	    default:                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_ENCODE_MISSINGFRAMES;         /*COVERAGE_IGNORE*/
	        ret = FALSE;                    /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag MissingFrames_Decode(MissingFrames* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint MissingFrames_index_tmp;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &MissingFrames_index_tmp, 0, 1);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_MISSINGFRAMES;
	if (ret) {
	    switch(MissingFrames_index_tmp)
	    {
	    case 0:
	    	pVal->kind = nr_PRESENT;
	    	ret = SequenceNumber_Decode((&(pVal->u.nr)), pBitStrm, pErrCode);
	    	break;
	    case 1:
	    	pVal->kind = span_PRESENT;
	    	ret = SequenceNumberSpan_Decode((&(pVal->u.span)), pBitStrm, pErrCode);
	    	break;
	    default:                        /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_DECODE_MISSINGFRAMES;     /*COVERAGE_IGNORE*/
	        ret = FALSE;                /*COVERAGE_IGNORE*/
	    }
	}  /*COVERAGE_IGNORE*/

	return ret  && MissingFrames_IsConstraintValid(pVal, pErrCode);
}


flag SREJ_missing_IsConstraintValid(const SREJ_missing* pVal, int* pErrCode)
{
    flag ret = TRUE;
    int i1;
    ret = (pVal->nCount <= 4);
    *pErrCode = ret ? 0 :  ERR_SREJ_MISSING;
    if (ret) {
        for(i1 = 0; ret && i1 < pVal->nCount; i1++)
        {
        	ret = MissingFrames_IsConstraintValid((&(pVal->arr[i1])), pErrCode);
        }
    }   /*COVERAGE_IGNORE*/

	return ret;
}

flag SREJ_IsConstraintValid(const SREJ* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = SequenceNumber_IsConstraintValid((&(pVal->nr)), pErrCode);
    if (ret) {
        ret = PollFinal_IsConstraintValid((&(pVal->pf)), pErrCode);
        if (ret) {
            ret = SREJ_missing_IsConstraintValid((&(pVal->missing)), pErrCode);
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void SREJ_missing_Initialize(SREJ_missing* pVal)
{
	(void)pVal;

    int i1;

	i1 = 0;
	while (i1< 4) {
	    MissingFrames_Initialize((&(pVal->arr[i1])));
	    i1 = i1 + 1;
	}
	pVal->nCount = 0;
}
void SREJ_Initialize(SREJ* pVal)
{
	(void)pVal;


	/*set nr */
	SequenceNumber_Initialize((&(pVal->nr)));
	/*set pf */
	PollFinal_Initialize((&(pVal->pf)));
	/*set missing */
	SREJ_missing_Initialize((&(pVal->missing)));
}

flag SREJ_Encode(const SREJ* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	int i1;
	*pErrCode = 0;
	ret = bCheckConstraints ? SREJ_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode nr */
	    ret = SequenceNumber_Encode((&(pVal->nr)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode pf */
	        ret = PollFinal_Encode((&(pVal->pf)), pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode missing */
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->missing.nCount, 0, 4);
	            for(i1=0; (i1 < (int)pVal->missing.nCount) && ret; i1++)
	            {
	            	ret = MissingFrames_Encode((&(pVal->missing.arr[i1])), pBitStrm, pErrCode, FALSE);
	            }
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag SREJ_Decode(SREJ* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	int i1;
	asn1SccSint nCount;

	/*Decode nr */
	ret = SequenceNumber_Decode((&(pVal->nr)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode pf */
	    ret = PollFinal_Decode((&(pVal->pf)), pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode missing */
	        ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 4);
	        *pErrCode = ret ? 0 : ERR_UPER_DECODE_SREJ_MISSING;
	        pVal->missing.nCount = (long)nCount;
	        for(i1=0; (i1 < (int)pVal->missing.nCount) && ret; i1++)
	        {
	        	ret = MissingFrames_Decode((&(pVal->missing.arr[i1])), pBitStrm, pErrCode);
	        }
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && SREJ_IsConstraintValid(pVal, pErrCode);
}


flag RR_IsConstraintValid(const RR* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = SequenceNumber_IsConstraintValid((&(pVal->nr)), pErrCode);
    if (ret) {
        ret = PollFinal_IsConstraintValid((&(pVal->pf)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void RR_Initialize(RR* pVal)
{
	(void)pVal;


	/*set nr */
	SequenceNumber_Initialize((&(pVal->nr)));
	/*set pf */
	PollFinal_Initialize((&(pVal->pf)));
}

flag RR_Encode(const RR* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? RR_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode nr */
	    ret = SequenceNumber_Encode((&(pVal->nr)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode pf */
	        ret = PollFinal_Encode((&(pVal->pf)), pBitStrm, pErrCode, FALSE);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag RR_Decode(RR* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode nr */
	ret = SequenceNumber_Decode((&(pVal->nr)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode pf */
	    ret = PollFinal_Decode((&(pVal->pf)), pBitStrm, pErrCode);
	}   /*COVERAGE_IGNORE*/

	return ret  && RR_IsConstraintValid(pVal, pErrCode);
}


flag Payload_IsConstraintValid(const Payload* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((1 <= pVal->nCount) && (pVal->nCount <= 384));
    *pErrCode = ret ? 0 :  ERR_PAYLOAD;

	return ret;
}

void Payload_Initialize(Payload* pVal)
{
	(void)pVal;


	memset(pVal->arr, 0x0, 384/8);

	pVal->nCount = 1;
}

flag Payload_Encode(const Payload* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? Payload_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 384);
	    BitStream_AppendBits(pBitStrm, pVal->arr, pVal->nCount);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag Payload_Decode(Payload* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint nCount;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 384);
	if (ret) {
		pVal->nCount = (long)nCount;
		ret = BitStream_ReadBits(pBitStrm, pVal->arr, pVal->nCount);
		*pErrCode = ret ? 0 : ERR_UPER_DECODE_PAYLOAD;
	}

	return ret  && Payload_IsConstraintValid(pVal, pErrCode);
}


flag Info_IsConstraintValid(const Info* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = SequenceNumber_IsConstraintValid((&(pVal->ns)), pErrCode);
    if (ret) {
        ret = SequenceNumber_IsConstraintValid((&(pVal->nr)), pErrCode);
        if (ret) {
            ret = PollFinal_IsConstraintValid((&(pVal->pf)), pErrCode);
            if (ret) {
                ret = Payload_IsConstraintValid((&(pVal->content)), pErrCode);
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void Info_Initialize(Info* pVal)
{
	(void)pVal;


	/*set ns */
	SequenceNumber_Initialize((&(pVal->ns)));
	/*set nr */
	SequenceNumber_Initialize((&(pVal->nr)));
	/*set pf */
	PollFinal_Initialize((&(pVal->pf)));
	/*set content */
	Payload_Initialize((&(pVal->content)));
}

flag Info_Encode(const Info* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? Info_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode ns */
	    ret = SequenceNumber_Encode((&(pVal->ns)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode nr */
	        ret = SequenceNumber_Encode((&(pVal->nr)), pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode pf */
	            ret = PollFinal_Encode((&(pVal->pf)), pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode content */
	                ret = Payload_Encode((&(pVal->content)), pBitStrm, pErrCode, FALSE);
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag Info_Decode(Info* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode ns */
	ret = SequenceNumber_Decode((&(pVal->ns)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode nr */
	    ret = SequenceNumber_Decode((&(pVal->nr)), pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode pf */
	        ret = PollFinal_Decode((&(pVal->pf)), pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode content */
	            ret = Payload_Decode((&(pVal->content)), pBitStrm, pErrCode);
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && Info_IsConstraintValid(pVal, pErrCode);
}


flag CRC16_IsConstraintValid(const CRC16* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void CRC16_Initialize(CRC16* pVal)
{
	(void)pVal;


	memset(pVal->arr, 0x0, 16/8);


}

flag CRC16_Encode(const CRC16* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? CRC16_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBits(pBitStrm, pVal->arr, 16);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag CRC16_Decode(CRC16* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBits(pBitStrm, pVal->arr, 16);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_CRC16;

	return ret  && CRC16_IsConstraintValid(pVal, pErrCode);
}


flag Packet_data_IsConstraintValid(const Packet_data* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case information_PRESENT : 
            ret = Info_IsConstraintValid((&(pVal->u.information)), pErrCode);
            break;          
        case receiverReady_PRESENT : 
            ret = RR_IsConstraintValid((&(pVal->u.receiverReady)), pErrCode);
            break;          
        case multiSelectiveReject_PRESENT : 
            ret = SREJ_IsConstraintValid((&(pVal->u.multiSelectiveReject)), pErrCode);
            break;          
        case setMode_PRESENT : 
            ret = SM_IsConstraintValid((&(pVal->u.setMode)), pErrCode);
            break;          
        case unnumberedAcknowledgement_PRESENT : 
            ret = UA_IsConstraintValid((&(pVal->u.unnumberedAcknowledgement)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_PACKET_DATA;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

flag Packet_IsConstraintValid(const Packet* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Packet_data_IsConstraintValid((&(pVal->data)), pErrCode);
    if (ret) {
        ret = CRC16_IsConstraintValid((&(pVal->sum)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void Packet_data_Initialize(Packet_data* pVal)
{
	(void)pVal;


	pVal->kind = information_PRESENT;
	Info_Initialize((&(pVal->u.information)));
}
void Packet_Initialize(Packet* pVal)
{
	(void)pVal;


	/*set data */
	Packet_data_Initialize((&(pVal->data)));
	/*set sum */
	CRC16_Initialize((&(pVal->sum)));
}

flag Packet_Encode(const Packet* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? Packet_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode data */
	    switch(pVal->data.kind)
	    {
	    case information_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 4);
	    	ret = Info_Encode((&(pVal->data.u.information)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case receiverReady_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 4);
	    	ret = RR_Encode((&(pVal->data.u.receiverReady)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case multiSelectiveReject_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 4);
	    	ret = SREJ_Encode((&(pVal->data.u.multiSelectiveReject)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case setMode_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 4);
	    	ret = SM_Encode((&(pVal->data.u.setMode)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case unnumberedAcknowledgement_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 4, 0, 4);
	    	ret = UA_Encode((&(pVal->data.u.unnumberedAcknowledgement)), pBitStrm, pErrCode, FALSE);
	    	break;
	    default:                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_ENCODE_PACKET_DATA;         /*COVERAGE_IGNORE*/
	        ret = FALSE;                    /*COVERAGE_IGNORE*/
	    }
	    if (ret) {
	        /*Encode sum */
	        ret = CRC16_Encode((&(pVal->sum)), pBitStrm, pErrCode, FALSE);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag Packet_Decode(Packet* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint Packet_data_index_tmp;

	/*Decode data */
	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &Packet_data_index_tmp, 0, 4);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_PACKET_DATA;
	if (ret) {
	    switch(Packet_data_index_tmp)
	    {
	    case 0:
	    	pVal->data.kind = information_PRESENT;
	    	ret = Info_Decode((&(pVal->data.u.information)), pBitStrm, pErrCode);
	    	break;
	    case 1:
	    	pVal->data.kind = receiverReady_PRESENT;
	    	ret = RR_Decode((&(pVal->data.u.receiverReady)), pBitStrm, pErrCode);
	    	break;
	    case 2:
	    	pVal->data.kind = multiSelectiveReject_PRESENT;
	    	ret = SREJ_Decode((&(pVal->data.u.multiSelectiveReject)), pBitStrm, pErrCode);
	    	break;
	    case 3:
	    	pVal->data.kind = setMode_PRESENT;
	    	ret = SM_Decode((&(pVal->data.u.setMode)), pBitStrm, pErrCode);
	    	break;
	    case 4:
	    	pVal->data.kind = unnumberedAcknowledgement_PRESENT;
	    	ret = UA_Decode((&(pVal->data.u.unnumberedAcknowledgement)), pBitStrm, pErrCode);
	    	break;
	    default:                        /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_DECODE_PACKET_DATA;     /*COVERAGE_IGNORE*/
	        ret = FALSE;                /*COVERAGE_IGNORE*/
	    }
	}  /*COVERAGE_IGNORE*/
	if (ret) {
	    /*Decode sum */
	    ret = CRC16_Decode((&(pVal->sum)), pBitStrm, pErrCode);
	}   /*COVERAGE_IGNORE*/

	return ret  && Packet_IsConstraintValid(pVal, pErrCode);
}


