#ifndef GENERATED_ASN1SCC_lora_layer_2_H
#define GENERATED_ASN1SCC_lora_layer_2_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef flag PollFinal;


#define ERR_POLLFINAL		1  /**/
flag PollFinal_IsConstraintValid(const PollFinal* pVal, int* pErrCode);

void PollFinal_Initialize(PollFinal* pVal);

#define ERR_UPER_ENCODE_POLLFINAL		2  /**/
#define PollFinal_REQUIRED_BYTES_FOR_ENCODING       1
#define PollFinal_REQUIRED_BITS_FOR_ENCODING        1

flag PollFinal_Encode(const PollFinal* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_POLLFINAL		3  /**/
flag PollFinal_Decode(PollFinal* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- SM --------------------------------------------*/
typedef struct {
    PollFinal p;

} SM;

#define ERR_SM		16  /**/
#define ERR_SM_P_2		11  /**/
flag SM_IsConstraintValid(const SM* pVal, int* pErrCode);

void SM_Initialize(SM* pVal);

#define ERR_UPER_ENCODE_SM		17  /**/
#define ERR_UPER_ENCODE_SM_P_2		12  /**/
#define SM_REQUIRED_BYTES_FOR_ENCODING       1
#define SM_REQUIRED_BITS_FOR_ENCODING        1

flag SM_Encode(const SM* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_SM		18  /**/
#define ERR_UPER_DECODE_SM_P_2		13  /**/
flag SM_Decode(SM* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- UA --------------------------------------------*/
typedef struct {
    PollFinal f;

} UA;

#define ERR_UA		31  /**/
#define ERR_UA_F_2		26  /**/
flag UA_IsConstraintValid(const UA* pVal, int* pErrCode);

void UA_Initialize(UA* pVal);

#define ERR_UPER_ENCODE_UA		32  /**/
#define ERR_UPER_ENCODE_UA_F_2		27  /**/
#define UA_REQUIRED_BYTES_FOR_ENCODING       1
#define UA_REQUIRED_BITS_FOR_ENCODING        1

flag UA_Encode(const UA* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_UA		33  /**/
#define ERR_UPER_DECODE_UA_F_2		28  /**/
flag UA_Decode(UA* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint SequenceNumber;


#define ERR_SEQUENCENUMBER		36  /*(0..127)*/
flag SequenceNumber_IsConstraintValid(const SequenceNumber* pVal, int* pErrCode);

void SequenceNumber_Initialize(SequenceNumber* pVal);

#define ERR_UPER_ENCODE_SEQUENCENUMBER		37  /**/
#define SequenceNumber_REQUIRED_BYTES_FOR_ENCODING       1
#define SequenceNumber_REQUIRED_BITS_FOR_ENCODING        7

flag SequenceNumber_Encode(const SequenceNumber* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_SEQUENCENUMBER		38  /**/
flag SequenceNumber_Decode(SequenceNumber* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- SequenceNumberSpan --------------------------------------------*/
typedef struct {
    SequenceNumber first;
    SequenceNumber last;

} SequenceNumberSpan;

#define ERR_SEQUENCENUMBERSPAN		61  /**/
#define ERR_SEQUENCENUMBERSPAN_FIRST_2		46  /**/
#define ERR_SEQUENCENUMBERSPAN_LAST_2		56  /**/
flag SequenceNumberSpan_IsConstraintValid(const SequenceNumberSpan* pVal, int* pErrCode);

void SequenceNumberSpan_Initialize(SequenceNumberSpan* pVal);

#define ERR_UPER_ENCODE_SEQUENCENUMBERSPAN		62  /**/
#define ERR_UPER_ENCODE_SEQUENCENUMBERSPAN_FIRST_2		47  /**/
#define ERR_UPER_ENCODE_SEQUENCENUMBERSPAN_LAST_2		57  /**/
#define SequenceNumberSpan_REQUIRED_BYTES_FOR_ENCODING       2
#define SequenceNumberSpan_REQUIRED_BITS_FOR_ENCODING        14

flag SequenceNumberSpan_Encode(const SequenceNumberSpan* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_SEQUENCENUMBERSPAN		63  /**/
#define ERR_UPER_DECODE_SEQUENCENUMBERSPAN_FIRST_2		48  /**/
#define ERR_UPER_DECODE_SEQUENCENUMBERSPAN_LAST_2		58  /**/
flag SequenceNumberSpan_Decode(SequenceNumberSpan* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- MissingFrames --------------------------------------------*/

typedef enum {
    MissingFrames_NONE,
    nr_PRESENT,
    span_PRESENT
} MissingFrames_selection;

typedef union {
    SequenceNumber nr;
    SequenceNumberSpan span;
} MissingFrames_unchecked_union;

typedef struct {
    MissingFrames_selection kind;

    MissingFrames_unchecked_union u;
} MissingFrames;

#define ERR_MISSINGFRAMES		81  /**/
#define ERR_MISSINGFRAMES_NR_2		71  /**/
#define ERR_MISSINGFRAMES_SPAN		76  /**/
flag MissingFrames_IsConstraintValid(const MissingFrames* pVal, int* pErrCode);

void MissingFrames_Initialize(MissingFrames* pVal);

#define ERR_UPER_ENCODE_MISSINGFRAMES		82  /**/
#define ERR_UPER_ENCODE_MISSINGFRAMES_NR_2		72  /**/
#define ERR_UPER_ENCODE_MISSINGFRAMES_SPAN		77  /**/
#define MissingFrames_REQUIRED_BYTES_FOR_ENCODING       2
#define MissingFrames_REQUIRED_BITS_FOR_ENCODING        15

flag MissingFrames_Encode(const MissingFrames* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_MISSINGFRAMES		83  /**/
#define ERR_UPER_DECODE_MISSINGFRAMES_NR_2		73  /**/
#define ERR_UPER_DECODE_MISSINGFRAMES_SPAN		78  /**/
flag MissingFrames_Decode(MissingFrames* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- SREJ --------------------------------------------*/


typedef struct {
    int nCount;
    MissingFrames arr[4];
} SREJ_missing;
typedef struct {
    SequenceNumber nr;
    PollFinal pf;
    SREJ_missing missing;

} SREJ;

#define ERR_SREJ_MISSING		111  /*(SIZE (0..4))*/
#define ERR_SREJ_MISSING_ELM		106  /**/
flag SREJ_missing_IsConstraintValid(const SREJ_missing* pVal, int* pErrCode);

#define ERR_SREJ		116  /**/
#define ERR_SREJ_NR_2		91  /**/
#define ERR_SREJ_PF_2		101  /**/
flag SREJ_IsConstraintValid(const SREJ* pVal, int* pErrCode);

void SREJ_missing_Initialize(SREJ_missing* pVal);
void SREJ_Initialize(SREJ* pVal);

#define ERR_UPER_ENCODE_SREJ		117  /**/
#define ERR_UPER_ENCODE_SREJ_NR_2		92  /**/
#define ERR_UPER_ENCODE_SREJ_PF_2		102  /**/
#define ERR_UPER_ENCODE_SREJ_MISSING		112  /**/
#define ERR_UPER_ENCODE_SREJ_MISSING_ELM		107  /**/
#define SREJ_REQUIRED_BYTES_FOR_ENCODING       9
#define SREJ_REQUIRED_BITS_FOR_ENCODING        71

flag SREJ_Encode(const SREJ* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_SREJ		118  /**/
#define ERR_UPER_DECODE_SREJ_NR_2		93  /**/
#define ERR_UPER_DECODE_SREJ_PF_2		103  /**/
#define ERR_UPER_DECODE_SREJ_MISSING		113  /**/
#define ERR_UPER_DECODE_SREJ_MISSING_ELM		108  /**/
flag SREJ_Decode(SREJ* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- RR --------------------------------------------*/
typedef struct {
    SequenceNumber nr;
    PollFinal pf;

} RR;

#define ERR_RR		141  /**/
#define ERR_RR_NR_2		126  /**/
#define ERR_RR_PF_2		136  /**/
flag RR_IsConstraintValid(const RR* pVal, int* pErrCode);

void RR_Initialize(RR* pVal);

#define ERR_UPER_ENCODE_RR		142  /**/
#define ERR_UPER_ENCODE_RR_NR_2		127  /**/
#define ERR_UPER_ENCODE_RR_PF_2		137  /**/
#define RR_REQUIRED_BYTES_FOR_ENCODING       1
#define RR_REQUIRED_BITS_FOR_ENCODING        8

flag RR_Encode(const RR* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_RR		143  /**/
#define ERR_UPER_DECODE_RR_NR_2		128  /**/
#define ERR_UPER_DECODE_RR_PF_2		138  /**/
flag RR_Decode(RR* pVal, BitStream* pBitStrm, int* pErrCode);

typedef struct {
    int nCount; /*Number of bits in the array. Max value is : 384 */
    byte arr[48];
} Payload;

#define ERR_PAYLOAD		146  /*(SIZE (1..384))*/
flag Payload_IsConstraintValid(const Payload* pVal, int* pErrCode);

void Payload_Initialize(Payload* pVal);

#define ERR_UPER_ENCODE_PAYLOAD		147  /**/
#define Payload_REQUIRED_BYTES_FOR_ENCODING       50
#define Payload_REQUIRED_BITS_FOR_ENCODING        393

flag Payload_Encode(const Payload* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PAYLOAD		148  /**/
flag Payload_Decode(Payload* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- Info --------------------------------------------*/
typedef struct {
    SequenceNumber ns;
    SequenceNumber nr;
    PollFinal pf;
    Payload content;

} Info;

#define ERR_INFO		191  /**/
#define ERR_INFO_NS_2		156  /**/
#define ERR_INFO_NR_2		166  /**/
#define ERR_INFO_PF_2		176  /**/
#define ERR_INFO_CONTENT_2		186  /**/
flag Info_IsConstraintValid(const Info* pVal, int* pErrCode);

void Info_Initialize(Info* pVal);

#define ERR_UPER_ENCODE_INFO		192  /**/
#define ERR_UPER_ENCODE_INFO_NS_2		157  /**/
#define ERR_UPER_ENCODE_INFO_NR_2		167  /**/
#define ERR_UPER_ENCODE_INFO_PF_2		177  /**/
#define ERR_UPER_ENCODE_INFO_CONTENT_2		187  /**/
#define Info_REQUIRED_BYTES_FOR_ENCODING       51
#define Info_REQUIRED_BITS_FOR_ENCODING        408

flag Info_Encode(const Info* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_INFO		193  /**/
#define ERR_UPER_DECODE_INFO_NS_2		158  /**/
#define ERR_UPER_DECODE_INFO_NR_2		168  /**/
#define ERR_UPER_DECODE_INFO_PF_2		178  /**/
#define ERR_UPER_DECODE_INFO_CONTENT_2		188  /**/
flag Info_Decode(Info* pVal, BitStream* pBitStrm, int* pErrCode);

typedef struct {
    byte arr[2];
} CRC16;

#define ERR_CRC16		196  /*(SIZE (16))*/
flag CRC16_IsConstraintValid(const CRC16* pVal, int* pErrCode);

void CRC16_Initialize(CRC16* pVal);

#define ERR_UPER_ENCODE_CRC16		197  /**/
#define CRC16_REQUIRED_BYTES_FOR_ENCODING       2
#define CRC16_REQUIRED_BITS_FOR_ENCODING        16

flag CRC16_Encode(const CRC16* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CRC16		198  /**/
flag CRC16_Decode(CRC16* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- Packet --------------------------------------------*/
/*-- Packet_data --------------------------------------------*/

typedef enum {
    Packet_data_NONE,
    information_PRESENT,
    receiverReady_PRESENT,
    multiSelectiveReject_PRESENT,
    setMode_PRESENT,
    unnumberedAcknowledgement_PRESENT
} Packet_data_selection;

typedef union {
    Info information;
    RR receiverReady;
    SREJ multiSelectiveReject;
    SM setMode;
    UA unnumberedAcknowledgement;
} Packet_data_unchecked_union;

typedef struct {
    Packet_data_selection kind;

    Packet_data_unchecked_union u;
} Packet_data;
typedef struct {
    Packet_data data;
    CRC16 sum;

} Packet;

#define ERR_PACKET_DATA		226  /**/
#define ERR_PACKET_DATA_INFORMATION		201  /**/
#define ERR_PACKET_DATA_RECEIVERREADY		206  /**/
#define ERR_PACKET_DATA_MULTISELECTIVEREJECT		211  /**/
#define ERR_PACKET_DATA_SETMODE		216  /**/
#define ERR_PACKET_DATA_UNNUMBEREDACKNOWLEDGEMENT		221  /**/
flag Packet_data_IsConstraintValid(const Packet_data* pVal, int* pErrCode);

#define ERR_PACKET		241  /**/
#define ERR_PACKET_SUM_2		236  /**/
flag Packet_IsConstraintValid(const Packet* pVal, int* pErrCode);

void Packet_data_Initialize(Packet_data* pVal);
void Packet_Initialize(Packet* pVal);

#define ERR_UPER_ENCODE_PACKET		242  /**/
#define ERR_UPER_ENCODE_PACKET_DATA		227  /**/
#define ERR_UPER_ENCODE_PACKET_DATA_INFORMATION		202  /**/
#define ERR_UPER_ENCODE_PACKET_DATA_RECEIVERREADY		207  /**/
#define ERR_UPER_ENCODE_PACKET_DATA_MULTISELECTIVEREJECT		212  /**/
#define ERR_UPER_ENCODE_PACKET_DATA_SETMODE		217  /**/
#define ERR_UPER_ENCODE_PACKET_DATA_UNNUMBEREDACKNOWLEDGEMENT		222  /**/
#define ERR_UPER_ENCODE_PACKET_SUM_2		237  /**/
#define Packet_REQUIRED_BYTES_FOR_ENCODING       54
#define Packet_REQUIRED_BITS_FOR_ENCODING        427

flag Packet_Encode(const Packet* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PACKET		243  /**/
#define ERR_UPER_DECODE_PACKET_DATA		228  /**/
#define ERR_UPER_DECODE_PACKET_DATA_INFORMATION		203  /**/
#define ERR_UPER_DECODE_PACKET_DATA_RECEIVERREADY		208  /**/
#define ERR_UPER_DECODE_PACKET_DATA_MULTISELECTIVEREJECT		213  /**/
#define ERR_UPER_DECODE_PACKET_DATA_SETMODE		218  /**/
#define ERR_UPER_DECODE_PACKET_DATA_UNNUMBEREDACKNOWLEDGEMENT		223  /**/
#define ERR_UPER_DECODE_PACKET_SUM_2		238  /**/
flag Packet_Decode(Packet* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
